### ISSUE TITLE
Benefits over native string comparison?

### ISSUE THREAD

**Issue by kkoskelin** [lukeed/sort-isostring#1]
If the items to be compared are string representations of ISO-8601 dates, what is the benefit of walking the lengths of the strings and comparing individual charCodes?

In one of my projects I compare these with native functionality of `date1 < date2`, `date1 == date2`, or `date1 > date2`. (Again where date1 and date2 are ISO-8601 strings like `YYYY-MM-DDThh:mm:ss.000Z`)

It might be instructive to provide test cases which reveal how your library demonstrates advantage

**Comment by crazy4groovy** [comment]
Ya, I think this lib is a joke. Unless there are performance benefits?? ISO string are already formatted in sort friendly ways.

**Comment by lukeed** [comment]
It's not a joke. For a long time this _did_ outperform `string[].sort()`. In Node 6.x, `sort-isostring` had a slight edge, and only in `Node 8.x` did native start sliding ahead. The browser landscape had more noticeable impact, but now it's likely not the case anymore either.

Glad to see that `string[].sort` now performs much better than `sort-isostring` – as it should always have:

```js
// Node 12.18
  string[].sort()                  x 2,423,250 ops/sec ±0.50% (91 runs sampled)
  string[] -> sort-isostring       x 1,421,864 ops/sec ±0.29% (96 runs sampled)

// Node 10.13
  string[].sort()                  x 1,933,298 ops/sec ±1.95% (93 runs sampled)
  string[] -> sort-isostring       x 1,524,128 ops/sec ±0.26% (92 runs sampled)
```

I forgot to check the new numbers before sharing this library. 
It was probably a mistake to release this – and so I'll be archiving the repo.

The only peace of mind left with this library is that it allows you to swap the comparison order easily.
I've found many teams' (and some of my own) code doing stuff like `dates.sort((a, b) => b.localeCompare(a))`, which kills your performance. Here are numbers for those:

```js
// Node 10.13
  string[].sort().reverse()                x 1,889,627 ops/sec ±1.76% (95 runs sampled)
  string[] -> sort-isostring(b,a)          x 1,661,203 ops/sec ±1.10% (93 runs sampled)
  string[].sort((a,b) => locale(b, a))     x   227,818 ops/sec ±0.46% (92 runs sampled)
  string[].sort((a,b) => b - a)            x 1,189,071 ops/sec ±0.29% (96 runs sampled)
```

Thanks for informing me. Will take care of it now
